### ISSUE TITLE
Ignoring password managers

### ISSUE THREAD

**Issue by iRomanyshyn** [popov895/Clipman#32]
Hi Eugene! People may need a  feature for ignoring password manager software. There are many password managers, I use KeePassXC and Firefox built-in. That's one thing that differentiates this extension from other cool clipboard managers like the Pano extension, or CopyQ application.

**Comment by popov895** [comment]
Clipman doesn't store passwords copied from KeePassXC because the latter marks them as sensitive data. For some reason, other password managers don't do this, so it's not possible to determine whether the copied data is sensitive or not. The solution that Pano uses is to not copy anything from the specified application, even if that data is not sensitive (for example, a link to a website or a note). IMO this is overkill.

I can recommend that you set a keyboard shortcut to quickly toggle private mode. Also, you can ask the developer of the password manager to add support for "x-kde-passwordManagerHint" mime type (or some kind of his own) for sensitive data.

**Comment by iRomanyshyn** [comment]
The other recommendation is to change the Clipman icon color to red or orange or change the shape to indicate it's in private mode as now it's not easy to understand when it is. Maybe add some notification on switching private mode on and off.

**Comment by popov895** [comment]
Interesting idea. Can you file a bug report about this?
