### ISSUE TITLE
Visual way to inform user about the status of Private Mode

### ISSUE THREAD

**Issue by iRomanyshyn** [popov895/Clipman#35]
Users may need good visual feedback on switching Private Mode on and off. My idea is to change the icon color and/or its shape. When the microphone is active, I found the microphone icon in the GNOME shell changes to [#FF7800](https://developer.gnome.org/hig/reference/palette.html?highlight=ff7800). So I propose to do the same thing when the Private Mode is active. Also, it would be nice to inform the user by the system notification about the mode change (or the thing used to visualize volume and brightness changes, it would be better because no one likes hundreds of repeated notifications) and/or by flashing the icon with different colors upon enabling and disabling (blink green on disabling the Private Mode, blink orange on enabling then leave orange), as for now there is no visual confirmation when switching modes. I don't have any experience in building GNOME extensions so it may be a little silly what I propose.

![Clipman](https://github.com/popov895/Clipman/assets/11888301/a9cc74cf-fa27-4e08-b222-653e260f2829)

**Comment by popov895** [comment]
Actually, starting with version 52 (or 55 on EGO), an additional icon is displayed next to the main icon to indicate that Private Mode is enabled.

![Screenshot from 2023-10-10 12-27-11](https://github.com/popov895/Clipman/assets/24252473/70a3bf73-a5a6-46db-9a6b-37a14e00c65d)

I decided not to change the color (or transparency) of the icon because, firstly, there're visually impaired people who may perceive colors differently, and secondly, I haven't seen the same solution used anywhere in GNOME (perhaps this changed in GNOME 45?).

> it would be nice to inform the user by the system notification about the mode change

I don't see any sense to use system notifications in this case, because toggling Private Mode is performed by the user himself.

**Comment by iRomanyshyn** [comment]
Yeah, I found this update after the system reboot. But using two icons can
confuse the user, it confused me a bit.

вт, 10 жовт. 2023 р. о 16:23 Eugene Popov ***@***.***> пише:
